#! /bin/bash

# This script will randomize the lines of the input and write them to output.
# The input file is unchanged.  The output file contains all the contents of
# the input file randomized.  
#
# Usage: randomizeLines < input_file > output_file
#
#
# The output from awk is piped through sort.  Sort uses on disk storage to
# minimize the memory it needs when performing sorts on large inputs.  By
# default sort uses /tmp as it's location for these temporary files (as
# used in this script).  If you are randomizing a large input file you may
# need a large amount of space in /tmp.

awk 'BEGIN{
   srand()
   i = 0
   while(getline){
      i++
      printf ("%d-%d:%s\n", rand() * 32768, i, $0) | "sort | sed s/.*://g"
   }
exit}'